server:
  port: 8080
spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-version: 0
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
warehouse:
  openapi:
    url: http://localhost:8080
